---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: robertdebock.update
      vars:
        update_reboot: false
        update_cache_valid_time: 1
        update_autoremove: false
...
