---
proxmox_aquabot:
  hosts:
    ct101:
      ansible_host: "192.168.0.101"
      ansible_host_key_checking: False      
      check_mode: False
    vm106:
      ansible_host: "192.168.0.106"
      ansible_host_key_checking: False
      check_mode: False
    vm151:
      ansible_host: "192.168.0.151"
      ansible_host_key_checking: False
      check_mode: False
    vm161:
      ansible_host: "192.168.0.161"
      ansible_host_key_checking: False
      check_mode: False
    vm162:
      ansible_host: "192.168.0.162"
      ansible_host_key_checking: False
      check_mode: False
    vm163:
      ansible_host: "192.168.0.163"
      ansible_host_key_checking: False
      check_mode: False
    vm164:
      ansible_host: "192.168.0.164"
      ansible_host_key_checking: False      
      check_mode: False      
    vm166:
      ansible_host: "192.168.0.166"
      ansible_host_key_checking: False      
      check_mode: False      
    vp169:
      ansible_host: "192.168.0.169"
      ansible_host_key_checking: False      
      check_mode: False

    vm152:
      ansible_host: "192.168.0.152"
      ansible_host_key_checking: False      
      check_mode: False  
    vm165:
      ansible_host: "192.168.0.165"
      ansible_host_key_checking: False      
      check_mode: False        

    vm167:
      ansible_host: "192.168.0.167"
      ansible_host_key_checking: False      
      check_mode: False       
    vm222:
      ansible_host: "192.168.0.165"
      ansible_host_key_checking: False      
      check_mode: False                   
    ct212:
      ansible_host: "192.168.0.212"
      ansible_host_key_checking: False      
      check_mode: False        

    vm153:
      ansible_host: "192.168.0.152"
      ansible_host_key_checking: False      
      check_mode: False  
    vm168:
      ansible_host: "192.168.0.168"
      ansible_host_key_checking: False      
      check_mode: False        
    vm170:
      ansible_host: "192.168.0.170"
      ansible_host_key_checking: False      
      check_mode: False        

...
